localstatedir = "w1"
logdir = "w1/log"
loglevel = "DEBUG"
rundir = "w1/run/gluster"
logfile = "w1.log"
peeraddress = "127.0.0.1:24008"
clientaddress = "127.0.0.1:24007"
etcdcurls = "http://127.0.0.1:2479"
etcdpurls = "http://127.0.0.1:2480"
restauth = true
