localstatedir = "w2"
logdir = "w2/log"
loglevel = "DEBUG"
rundir = "w2/run/gluster"
logfile = "w2.log"
peeraddress = "127.0.0.1:23008"
clientaddress = "127.0.0.1:23007"
etcdcurls = "http://127.0.0.1:2379"
etcdpurls = "http://127.0.0.1:2380"
restauth = true
