localstatedir = "w3"
logdir = "w3/log"
loglevel = "DEBUG"
rundir = "w3/run/gluster"
logfile = "w3.log"
peeraddress = "127.0.0.1:22008"
clientaddress = "127.0.0.1:22007"
etcdcurls = "http://127.0.0.1:2279"
etcdpurls = "http://127.0.0.1:2280"
restauth = true
