workdir = "/tmp/gd2_func_test/w4"
logfile = "w4.log"
peeraddress = "127.0.0.1:21008"
clientaddress = "127.0.0.1:21007"
etcdcurls = "http://127.0.0.1:2179"
etcdpurls = "http://127.0.0.1:2180"
restauth = true
